web/router.ex
defmodule Nimbus2000.Router do
  use Nimbus2000.Web, :router
  use Passport

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :assign_current_user
    plug :current_user
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", Nimbus2000 do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    get "/login", SessionController, :new
    post "/session", SessionController, :create
    get "/logout", SessionController, :delete
    get "/join", RegistrationController, :new
    post "/register", RegistrationController, :create
    get "/passwords/new", PasswordController, :new
    post "/passwords", PasswordController, :reset
    get "/404", PageController, :error404
    get "/*path", PageController, :index
  end

  # Other scopes may use custom stacks.
  scope "/api", Nimbus2000 do
    pipe_through :api

    resources "/drives", HardDriveController, except: [:new, :edit]
  end

  # Fetch the current user from the session and add it to `conn.assigns`. This
  # will allow you to have access to the current user in your views with
  # `@current_user`.
  defp assign_current_user(conn, _) do
   assign(conn, :current_user, get_session(conn, :current_user))
  end


end

web/controllers/session_controller.ex
defmodule Nimbus2000.SessionController do
  use Nimbus2000.Web, :controller

  alias Nimbus2000.User
  alias Passport.Session


  def new(conn, _) do
    conn
    |> check_login()
    |> render(:new)
  end

  def create(conn, %{"session" => %{"email" => email, "password" => pass}}) do
    check_login(conn)
    case Session.login(conn, String.downcase(email), pass) do
    {:ok, conn} ->
      conn
      |> redirect(to: page_path(conn, :index))
    {:error, _reason, conn} ->
      conn
      |> put_flash(:error, "Invalid username/password combination")
      |> render(:new)
    end
  end

  def delete(conn, _) do
    conn
    |> Session.logout()
    |> put_flash(:info, "You have been logged out")
    |> redirect(to: session_path(conn, :new))
  end

  defp check_login(conn) do
    if conn.assigns[:current_user] do
      conn
      |> redirect(to: page_path(conn, :index))
      |> halt
    else
      conn
    end
  end
end

web/views/session_view.ex
defmodule Nimbus2000.SessionView do
  use Nimbus2000.Web, :view
end

web/templates/session/new.html.eex
<div class="container" style="margin-top: 15vh;">
  <div class="centered empty shadow text-center col-4 col-lg-12">
    <div class="empty-title">
      <h1><i class="fa fa-unlock-alt" aria-hidden="true" style="margin-right:1rem;"></i> Login</h1>
    </div>
    <%= render Nimbus2000.LayoutView, "flash.html", conn: @conn %>
    <%= form_for @conn, session_path(@conn, :create), [as: :session], fn f -> %>
      <div class="centered bg-white light-shadow orange mt-20 pl-40 pt-40 pr-40 pb-40">
        <div class="form-group">
          <div class="form-label text-left" for="login-email">
            Email Address
          </div>
          <%= if value = get_flash(@conn, :value) do %>
            <%= text_input f, :email, placeholder: "@film-45.com", class: "form-input", id: "login-email", value: value %>
          <% else %>
            <%= text_input f, :email, placeholder: "@film-45.com", class: "form-input", id: "login-email", autofocus: "" %>
          <% end %>
        </div>
        <div class="form-group">
          <div class="form-label text-left" for="login-pw">
            Password
          </div>
          <%= if value = get_flash(@conn, :value) do %>
            <%= password_input f, :password, placeholder: "Password", class: "form-input input", id: "login-pw", autofocus: "" %>
          <% else %>
            <%= password_input f, :password, placeholder: "Password", class: "form-input input", id: "login-pw" %>
          <% end %>
            <%= link "Forgot Password?", to: password_path(@conn, :new), method: :get, class: "btn btn-link float-right" %>
        </div>
      </div>

      <hr class="mt-20 mb-20" />

      <div class="columns empty-action clearfix" style="clear:both;">
        <div class="col-6 container">
          <%= submit "Log in", class: "btn col-8 col-sm-12 float-right" %>
        </div>
        <div class="col-6 container">
          <%= link "Return to Homepage", to: page_path(@conn, :index), method: :get, class: "btn btn-link float-left"%>
        </div>
      </div>
    <% end %>
  </div>
</div>