web/router.ex
defmodule Nimbus2000.Router do
  use Nimbus2000.Web, :router
  use Passport

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :assign_current_user
    plug :current_user
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", Nimbus2000 do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    get "/login", SessionController, :new
    post "/session", SessionController, :create
    get "/logout", SessionController, :delete
    get "/join", RegistrationController, :new
    post "/register", RegistrationController, :create
    get "/passwords/new", PasswordController, :new
    post "/passwords", PasswordController, :reset
    get "/404", PageController, :error404
    get "/*path", PageController, :index
  end

  # Other scopes may use custom stacks.
  scope "/api", Nimbus2000 do
    pipe_through :api

    resources "/drives", HardDriveController, except: [:new, :edit]
  end

  # Fetch the current user from the session and add it to `conn.assigns`. This
  # will allow you to have access to the current user in your views with
  # `@current_user`.
  defp assign_current_user(conn, _) do
   assign(conn, :current_user, get_session(conn, :current_user))
  end


end

web/templates/page/404.html.eex
<div class="centered empty shadow text-center col-8 col-lg-10 mt-40">
  <div class="empty-title">
    <h4 class="red"> <i class="fa fa-exclamation-triangle mr-5"></i>  404</h4>
  </div>
  <hr/>
  <p class="empty-meta">
    We couldn't find the page you were looking for :(
    <br/>
    <br/>
  </p>
</div>

web/templates/page/index.html.eex
<%= if @current_user do %>

  <div class="ml-10 mr-10">
  <%= render Nimbus2000.LayoutView, "flash.html", conn: @conn %>
  </div>
  <%= tag :meta, name: "token", content: Phoenix.Token.sign(@conn, "nimbus2000TokenSalt", @current_user.id) %>
  <%= tag :meta, name: "log-out", content: session_path(@conn, :delete) %>
  <%= tag :meta, name: "home", content: page_path(@conn, :index) %>
  <%= if Mix.env == :dev do %>
    <%= tag :meta, name: "server", content: ("WSS://" <> @conn.host() <> ":" <> (to_string @conn.port()) <> "/socket/websocket") %>
  <%= else %>
    <%= tag :meta, name: "server", content: "WSS://" <> @conn.host() <> ":443/socket/websocket" %>
  <%= end %>
<% else %>
  <%= render Nimbus2000.LayoutView, "flash.html", conn: @conn %>
  <div class="container" style="margin-top: 15vh;">
    <div class="centered empty shadow text-center col-8 col-lg-12 slide-down">
      <div class="empty-title">
        <h1>The Magi</h1>
      </div>
      <hr/>
      <p class="empty-meta">
        The New <b>Drive-Tracker / Media-Finder / Life-Saver</b> of <b  class="logo">FILM <g class="orange">45</g></b>
        <br/>
        <br/>
      </p>
      <div class="columns empty-action">
        <span class="col-6 container">
          <%= button "Login", to: session_path(@conn, :new), method: :get , class: "btn-primary col-4 col-sm-12 float-right"%>
        </span>
        <span class="col-6 container">
          <%= button "Register", to: registration_path(@conn, :new), method: :get, class: "btn btn-link col-4 col-sm-12 float-left"%>
        </span>
      </div>
    </div>
  </div>
<% end %>